Introduced new options to download function
BU-ISCIII/relecov-tools pull request #226
Opened 2023-02-17 11:15 UTC by Shettland

Introduced a new flag to select which folders are going to be downloaded, for which I introduced a checkbox if the flag is given empty. It will still download everything by default if the flag is not given. 

Also, I changed the validation process of the download packages so It's done before downloading everything, using the metadata as reference.  I didn't remove the previous validation method though, so now it should validate the downloaded packages twice.

2023-02-20 09:53 UTC, saramonzon commented
This is from old code, but I'll take de chance to review the entire code xD
https://github.com/BU-ISCIII/relecov-tools/blob/f48b28d5aa9ba5e512dfe6e868d421a3c041f778/relecov_tools/sftp_handle.py#L303-L307

In the config file we have the complete heading for metadata lab file so I think we can just grab the column we need.

2023-02-20 10:27 UTC, saramonzon commented
delete code related to sftp_info api request as this is done with the update db module: 

https://github.com/BU-ISCIII/relecov-tools/blob/f48b28d5aa9ba5e512dfe6e868d421a3c041f778/relecov_tools/conf/configuration.json#L193

https://github.com/BU-ISCIII/relecov-tools/blob/f48b28d5aa9ba5e512dfe6e868d421a3c041f778/relecov_tools/sftp_handle.py#L365-L379

https://github.com/BU-ISCIII/relecov-tools/blob/f48b28d5aa9ba5e512dfe6e868d421a3c041f778/relecov_tools/sftp_handle.py#L109-L112

2023-02-20 10:40 UTC, saramonzon requested changes
Thanks for the PR @Shettland !! It looks very promising :) 

Please take a look to the comments, and please review the code removing anything that is not being used. If you feel more comfortable comment the code and I will double check if it is safe to remove it. But don't worry, we can always go back.

Also please, try this code with the FISABIO folder with the 100 samples and share here the log, the stdout when you run the module and the resulting folder with all the downloads. I think you said there were some problems with the metadata file, so if it is not possible to download it's fine, just the log to see if everything seems correct and if we can use it as info for the lab.

2023-02-20 10:40 UTC, saramonzon commented on relecov_tools/sftp_handle.py
> +        )
there are two possible allower extensions, fasta and fastq.gz, you should use the config parameter instead of using `fastq.gz` explicity here.

2023-02-20 10:40 UTC, saramonzon commented on relecov_tools/sftp_handle.py
> +    def validate_fetched_files(self, fetched_folder):
I think I will make two functions, one for validating the metadata file and another one to validate the files and if they match with the metadata.

2023-02-20 23:22 UTC, Shettland commented
I separated the validation process into three functions in order to make it more simple. I also implemented the different changes that you commented but I didn't remove anything except the lines of code that you described. There's still some changes that can be made regarding the column selection, I just thought that since that function worked fine you didn't want to change it.

Right now the metadata file uploaded to the server has wrong information. Hence, I cannot test if it works fine because the download process will always fail due to that.

2023-02-21 08:35 UTC, Shettland commented
I'll leave the log file for the last run of download with --target_folders activated:
[relecov.log](https://github.com/BU-ISCIII/relecov-tools/files/10791324/relecov.log)

2023-02-21 09:51 UTC, Shettland commented
I included some log infos to ease debugging. I'll leave the new log file that shows some of them for comparison:
[relecov.log](https://github.com/BU-ISCIII/relecov-tools/files/10792135/relecov.log)

2023-02-21 10:20 UTC, saramonzon approved these changes

2023-02-21 10:20 UTC, merged