Changes in the json files related with read-lab-metadata.py along with adaptations of the code to the new structure
BU-ISCIII/relecov-tools pull request #229
Opened 2023-03-02 16:45 UTC by Shettland

In order to simplify some parts of the code and to be make it more flexible to different options, many changes were made:
1) The first step was to replace  '_ _ all _ _' as a field possibility for the actual fields that compose the mapped field in [configuration.json](https://github.com/BU-ISCIII/relecov-tools/blob/develop/relecov_tools/conf/configuration.json) 
2) To make it functional, not only a few changes were made in the process_from_json and adding_fields methods from [read_lab_metadata.py](https://github.com/BU-ISCIII/relecov-tools/blob/develop/relecov_tools/read_lab_metadata.py), but also the structure of [laboratory_address.json](https://github.com/BU-ISCIII/relecov-tools/blob/develop/relecov_tools/conf/laboratory_address.json) and [submitter_address.json](https://github.com/BU-ISCIII/relecov-tools/blob/develop/relecov_tools/conf/submitter_address.json) were changed to dictionary of dictionaries (previously a list of dictionaries) as a means to make the structure of every json file as homogeneous as possible.
3) Along with that, a new function inside [sftp_handle.py](https://github.com/BU-ISCIII/relecov-tools/blob/develop/relecov_tools/sftp_handle.py) was included to map for different R1 and R2 descriptors in file names, in order to make the method "create_tmp_files_with_metadata_info" more flexible. The different allowed delimiters were included in [configuration.json](https://github.com/BU-ISCIII/relecov-tools/blob/develop/relecov_tools/conf/configuration.json).
4) The fields from [submitter_address.json](https://github.com/BU-ISCIII/relecov-tools/blob/develop/relecov_tools/conf/submitter_address.json) were included in [laboratory_address.json](https://github.com/BU-ISCIII/relecov-tools/blob/develop/relecov_tools/conf/laboratory_address.json) as a means to reduce the number of files needed.

2023-03-02 19:52 UTC, saramonzon requested changes

2023-03-02 19:52 UTC, saramonzon commented on relecov_tools/conf/configuration.json
> +    "allowed_R1_delimiters": [
mm don't know if we can add this under "sftp_module" so config file is more organized, and we know which params are used in each module? We can create also a general/main/whatever name suits you, for variables/params that are commonly used for all modules? I mean
```
{
   general: {
       ...
   }, 
   sftp_handle: {
  ...
   }, 
   read_metadata_lab{
   ....
   }
}
```
what do you think as a dev that sees the code for the first time, would that be useful for debugging? or would it make it more confusing?

2023-03-03 10:28 UTC, Shettland commented on relecov_tools/read_lab_metadata.py
> +            "sequence_file_R2_fastq" "sequence_file_R1_md5",
You are right, I missed that one.

2023-03-03 10:29 UTC, Shettland commented on relecov_tools/conf/submitter_address.json
> +{
Yes, it can be deleted as it has no purpose right now.

2023-03-03 10:32 UTC, Shettland commented on relecov_tools/read_lab_metadata.py
> +                        {str(map_field)}. Set as not provided"
No, right now if the key cannot be found it just interrupts the process. I forgot to change that log.error, it should say "Aborting" after the dot.

2023-03-03 10:44 UTC, Shettland commented on relecov_tools/conf/configuration.json
> +    "allowed_R1_delimiters": [
I like the idea, although that would need small changes in the code. I think I can work on that.

2023-03-03 14:10 UTC, merged